### PR TITLE
distribution/dump: open-source library

### PR DESCRIPTION
**Pull request by thrix**
Open source distribution/dump library from latest version
in downstream.

After accepted we should create move the downstream library
to a wrapper to this library.

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

### CODE REVIEW

**Comment by thrix** [comment]
@psss @sopos @amahdal can you pls review?

**Comment by AloisMahdal** [comment]
LGTM.

Maybe minor nitpick: the Author/description part can be removed from *runtest.sh* and *lib.sh*.

**Review by AloisMahdal — APPROVED** [review]
LGTM.

Maybe minor nitpick: the Author/description part can be removed from *runtest.sh* and *lib.sh*.

**Comment by thrix** [comment]
ack, removing

**Comment by thrix** [comment]
Fixed

**Comment by thrix** [comment]
@sopos seems this is good to go

**Comment by sopos** [comment]
thanks for the review

**Pull request merged**
