### PR TITLE
Move lib from downstream to beakerlib/distribution

### PR DESCRIPTION
**Pull request by Koncpa**

### CODE REVIEW

**Comment by Koncpa** [comment]
Moving because some conflicts in current test, where some test need to use beakerlib/distribution libs and also distribution libs from downstream. Runnin via tmt causing this sort of issue.

`    Library 'distribution/authconf' with url 'https://github.com/beakerlib/distribution' conflicts with already fetched library from 'https://pkgs.devel.redhat.com/git/tests/distribution'.`

**Comment by sopos** [comment]
The library requires the pam library as well. Having it in the upstream without the further requirements does not really make sense. It would be good to make the pam one upstream as well.

**Comment by sopos** [comment]
I've created the pam repo so it can be placed there.

**Comment by Koncpa** [comment]
@sopos I added pam here: https://github.com/beakerlib/pam and adjust **main.fmf** to require pam lib.

**Pull request merged**
